### ISSUE TITLE
CT The shape of the node highlight should be set by now

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#71] opened 2022-02-18 16:25 UTC
```
quadrilateral : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1645192507258%22%2C%22timestamp%22%3A1645195133897%7D&brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: The shape of the Node highlight should be set by now. Does it have bounds?
Error: Assertion failed: The shape of the Node highlight should be set by now. Does it have bounds?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/assert/js/assert.js:25:13)
at HighlightOverlay.activateHighlight (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/scenery/js/overlays/HighlightOverlay.js:232:17)
at HighlightOverlay.activateFocusHighlight (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/scenery/js/overlays/HighlightOverlay.js:278:10)
at HighlightOverlay.onFocusChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/scenery/js/overlays/HighlightOverlay.js:561:12)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/axon/js/Property.js:228:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/axon/js/Property.js:159:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/axon/js/Property.js:298:10)
at Function.set pdomFocus [as pdomFocus] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/scenery/js/accessibility/FocusManager.js:132:44)
at Object.blur (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/scenery/js/input/PDOMPointer.js:66:34)
id: Bayes Chrome
Snapshot from 2/18/2022, 6:55:07 AM

----------------------------------

quadrilateral : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1645192507258%22%2C%22timestamp%22%3A1645195806174%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Must one one and only one intersection between lines
Error: Assertion failed: Must one one and only one intersection between lines
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/quadrilateral/js/quadrilateral/view/RightAngleIndicatorNode.js:42:19
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/axon/js/Property.js:228:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/axon/js/Property.js:159:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/axon/js/DerivedProperty.js:98:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/axon/js/Property.js:228:23)
at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/axon/js/Property.js:159:14)
at SideNode.moveVerticesFromModelDelta (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/quadrilateral/js/quadrilateral/view/SideNode.js:190:42)
id: Bayes Chrome
Snapshot from 2/18/2022, 6:55:07 AM

----------------------------------

quadrilateral : voicing-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/quadrilateral/quadrilateral_en.html?continuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22voicing-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1645192507258%22%2C%22timestamp%22%3A1645194735947%7D&brand=phet&ea&fuzzBoard&voicingInitiallyEnabled&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&voicingInitiallyEnabled&memoryLimit=1000
Uncaught Error: Assertion failed: The shape of the Node highlight should be set by now. Does it have bounds?
Error: Assertion failed: The shape of the Node highlight should be set by now. Does it have bounds?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/assert/js/assert.js:25:13)
at HighlightOverlay.activateHighlight (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/scenery/js/overlays/HighlightOverlay.js:232:17)
at HighlightOverlay.activateFocusHighlight (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/scenery/js/overlays/HighlightOverlay.js:278:10)
at HighlightOverlay.onFocusChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/scenery/js/overlays/HighlightOverlay.js:561:12)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/axon/js/Property.js:228:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/axon/js/Property.js:159:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/axon/js/Property.js:298:10)
at Function.set pdomFocus [as pdomFocus] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/scenery/js/accessibility/FocusManager.js:132:44)
at Object.blur (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645192507258/chipper/dist/js/scenery/js/input/PDOMPointer.js:66:34)
id: Bayes Chrome
Snapshot from 2/18/2022, 6:55:07 AM
```

**Comment by jessegreenberg** [comment] 2022-02-18 17:50
Thanks @KatieWoe, caused by changes in #60. Fixed in the above commit by removing the cutsom focus highlight which isn't necessayr. Closing.

**Closed by jessegreenberg** 2022-02-18 17:50 UTC
Labels: type:automated-testing
