### ISSUE TITLE
CT PhET-iO API error:

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#145] opened 2022-05-09 14:48 UTC
```
quadrilateral : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652044800648/phet-io-wrappers/state/?sim=quadrilateral&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652044800648%22%2C%22timestamp%22%3A1652049765252%7D
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
quadrilateral.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.selectedTabProperty: 1. After startup, only dynamic instances prescribed by the baseline file can be registered.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652044800648/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.js:228:14)
at assertAPIError (phetioAPIValidation.js:141:15)
at listener (Timer.ts:33:10)
at listener (TinyEmitter.ts:93:8)
at emit (Sim.ts:963:24)
id: Bayes Chrome
Snapshot from 5/8/2022, 3:20:00 PM

----------------------------------

quadrilateral : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652044800648/studio/?sim=quadrilateral&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22quadrilateral%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652044800648%22%2C%22timestamp%22%3A1652069927696%7D
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
quadrilateral.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.selectedTabProperty: 1. After startup, only dynamic instances prescribed by the baseline file can be registered.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652044800648/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.js:228:14)
at assertAPIError (phetioAPIValidation.js:141:15)
at listener (Timer.ts:33:10)
at listener (TinyEmitter.ts:93:8)
at emit (Sim.ts:963:24)
id: Bayes Chrome
Snapshot from 5/8/2022, 3:20:00 PM
```

**Comment by jessegreenberg** [comment] 2022-05-09 15:32
Thanks @KatieWoe. This is a common code component and should not be specific to quadrilateral. It isn't showing up in ratio-and-proportion because that sim disables phet-io-state in https://github.com/phetsims/perennial/blob/5f8f275c58ddc2aee22a322cf81f60a74bbebc19/data/phet-io-state-unsupported#L12. 

We would expect this to be showing up in john-travoltage and friction and we are not sure why it isn't.

When I try to reproduce locally I am seeing a different DAG related error that is not happening in phet brand.
> Assertion failed:  This node is already managed by a layout container - make sure to wrap it in a Node if DAG, removing it from an old layout container, etc.

phet-io state is not a requirement of quadrilateral for the foreseeable future so am going to add this sim to perennial/data/phet-io-state-unsupported. I discussed with @zepumph over slack and he recommended to close this issue at this time.

**Closed by jessegreenberg** 2022-05-09 15:32 UTC
Labels: type:automated-testing
