### ISSUE TITLE
Description for 'opt/alt + C' unclear

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/quadrilateral#322] opened 2023-01-10 17:25 UTC
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.1

**Browser**
safari 16.1

**Problem description**
For https://github.com/phetsims/qa/issues/879, in the Keyboard Shortcuts dialog, for "With Voicing enabled, Check Current Shape" I was expecting to hear the actual shape when I press `option` + `c`, but I only hear properties when the shape name is hidden. It took me a minute to realize why I was sometimes hearing the name and sometimes wasn't. Perhaps there is a way to make this clearer in the description for `option` + `c` ? 

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Quadrilateral‬
URL: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.73/phet/quadrilateral_all_phet.html
Version: 1.0.0-dev.73 2023-01-08 23:48:12 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1475x780
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment] 2023-01-10 17:35
Thanks @Nancy-Salpepi. Removing my assignment but assigning @BLFiedler to review this design recommendation.

**Comment by Nancy-Salpepi** [comment] 2023-01-10 17:42
Also, with the Shape Name hidden, the information given with opt/alt + C is inconsistent. For some shapes only information about the sides is given (ex. rhombus, parallelogram), for others only angles are mentioned (ex. Rectangle), and with some shapes I hear info about both (ex. Square).

**Comment by terracoda** [comment] 2023-01-18 02:35
@BLFiedler, in [#333](https://github.com/phetsims/quadrilateral/issues/333#issuecomment-1384472720) Iist out side-by-side the key-shape-property Context Response and the full shape-defining State Description that is available when one plays the Current Details button.

Do you think a learner should be able to check the shape name without toggling the Shape Name Hidden button?

My original thought for this shortcut was that it would be a quick way to replay the "currently displayed" shape information, that is either:
- the shape's name when shape name is shown, or
- the shape's defining transformation property/properties when the shape name is hidden.

Personally, I thought that being able to re-voice that shape transformation property (when shape name is hidden) would help learners attend to and make sense of that information.

I closed #333 because that's how it was designed. Now I am second guessing myself.

@BLFiedler, do you think there should be a shortcut to just simple voice the shape name, or should we leave it as designed - voicing the shape name or shape information depending on what is visibly displayed?

If we leave it as-is, I can adjust the language in the keyboard shortcuts dialog.

**Comment by terracoda** [comment] 2023-01-18 03:29
Also, the current design is a way to hear the shape transformation property/ies when Voicing is enabled but context responses is not checked.

Considering that use case, I like the current design.

**Comment by terracoda** [comment] 2023-01-18 15:47
@BLFiedler, my main design question is whether we leave it as-is, or provide a more detailed context response to replace the shape-transformation context response. This new context response would be more like (but still different from) the details button.

Square:
- All corners right angles. All sides equal.

Rectangle:
- All corners right angles. Opposite sides equal.

Parallelogram: 
- Opposite corners equal. Opposite sides equal and parallel.

Rhombus:
- Opposite corners equal. All sides equal. 

Kite:
- One pair of opposite corners equal. Pairs of adjacent sides equal.

Dart:
- One pair of opposite corners are equal. Pairs of adjacent sides are equal. One corner points inward.

Concave Quadrilateral:
- Details for this shape can vary a little, here's two examples:
    - No corners equal. No sides are equal, no sides in parallel. One corner points inward.  
    - No corners equal. One pair of adjacent sides are equal, no sides in parallel. One corner points inward.

Convex Quadrilateral:
- Details for this shape can vary a little, here's two examples:
    - No corners equal. One pair of adjacent sides equal. No sides in parallel.
    - No corners equal. No sides equal. No sides in parallel.
    -No corners equal. Pairs of adjacent sides equal. No sides in parallel.

While helpful, I don't think these more detailed "check-shape" context responses would evoke the same kinds of questions from learners which could restrict the use of the tool in class rooms.

I think I have talked myself through this design problem. 

@BLFiedler, unless you see a real benefit to changing the current check-shape response, I think I am comfortable with leaving it as-is.

**Comment by terracoda** [comment] 2023-01-18 15:56
New description for Keyboard Shortcuts dialog.
Change:
-  "With Voicing enabled Check Current Shape" (apologies for bad caps here)

To:
- With Voicing enabled, check current shape name or properties.

If the above is too long:
- With Voicing enabled, check shape name or properties.

**Comment by terracoda** [comment] 2023-01-18 19:08
Thanks @BLFiedler, assigning to @jessegreenberg to update the dialog. I couldn't find the string.

**Comment by terracoda** [comment] 2023-01-26 15:28
<img width="887" alt="image" src="https://user-images.githubusercontent.com/1902116/214875370-0732a3d5-b4cd-415d-b184-b86178b3549d.png">

Hmm, nothing else has a visual period. Sorry about that @jessegreenberg. I need to document this. I checked RaP and Faraday's Law, and there are no visual periods in the Keyboard Shortcut dialogs. However, of course, we need periods for the accessible content read out from the PDOM.

@jessegreenberg, can you remove the visual period, and keep the period in the A11y View, just like we have done for other sims.

**Comment by terracoda** [comment] 2023-01-26 15:52
Everything else looks good.

**Comment by terracoda** [comment] 2023-01-26 15:55
Oh, the accessible content in the A11y View hasn't been updated. I'll see if I can do that.

**Comment by terracoda** [comment] 2023-01-26 16:57
I am going to try to update the ts file.

**Comment by terracoda** [comment] 2023-01-26 17:21
I made the change locally. Ping me when you are working on Quad.

**Comment by jessegreenberg** [comment] 2023-01-26 23:22
@terracoda and I met today for this and made the commit. Anything else here @terracoda?

**Comment by terracoda** [comment] 2023-01-26 23:34
Nope, all good.

**Closed by terracoda** 2023-01-26 23:34 UTC
Labels: dev:description, dev:voicing
