### ISSUE TITLE
angleToleranceIntervalProperty creates inconsistencies for determining isParallelogramProperty value

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#26] opened 2021-11-02 19:25 UTC
The tolerance makes it easier to hit a parallelogram, but it is also making it inconsistent when moving more than one vertex at a time. The following IS a parallelogram:

![image](https://user-images.githubusercontent.com/6396244/139931770-6b9437d4-6711-446d-b6ff-01ec2c7e0686.png)

vertex1.angleProperty: 1.9394583526356983
vertex2.angleProperty: 1.163663856846046
vertex3.angleProperty:  1.9289698148082035
vertex4.angleProperty: 1.2510932828896397

Dragging the right side to the left should keep the quad a parallelogram, but it currently does not.
![image](https://user-images.githubusercontent.com/6396244/139933920-8305f4f8-809b-4b1d-b605-1f606db6a73a.png)

vertex1.angleProperty: 1.923615974711773
vertex2.angleProperty: 1.1795062347699712
vertex3.angleProperty: 1.8802273644623
vertex4.angleProperty: 1.2998357332355432

**Comment by jessegreenberg** [comment] 2021-11-02 19:27
The tolerance is 0.1 radians, and you can see that the difference between angles vertex2 and vertex4 is larger than that.

**Comment by BLFiedler** [comment] 2021-11-03 14:04
Just as a quick thought - I don't know that this will result in a permanent fix perse, but MK and I found it useful to turn the most important toleranceinterval constants into query parameters so we could play around a little bit and see what "felt good". I believe with the intention to clean them up prior to publication. Would that be a possibility for angleToleranceIntervalProperty for now?

**Comment by jessegreenberg** [comment] 2021-11-09 18:16
Discussed today, the next step will be to add a query parameter as described above. Then we can return to this.

**Comment by jessegreenberg** [comment] 2021-11-09 18:27
We discussed today that potentially snapping vertices will be a way to solve this. We would need to know the "parallelogram position" for each vertex that is being dragged and set the position in response to a particular kind of input. We are not sure exactly how that will work so we are tabling the details for now but will likely come back to this in the coming weeks.

**Comment by jessegreenberg** [comment] 2021-11-09 21:30
A query parameter has been added for the value of the the angle tolerance interval called `?angleToleranceInterval` - it is in **radians**. It takes a value from 0 to 2 * Math.PI. The larger the value, the easier it is to create a parallelogram, with a value of 2* Math.PI making it imposible to leave the parallelogram state.

@BLFiedler can you please review this and comment on next steps when appropriate?

**Comment by BLFiedler** [comment] 2021-11-10 15:21
I am a bit more convinced after playing with this that we'll need either snapping correction behavior AND/OR that the ToleranceInterval for maintaining a parallelogram may need to widen while multiple things are under control/moving (two distinct cases, I know).

On that note - I do side dragging to be less of an issue if we make the angleToleranceInterval value smaller, since it requires you to find a "more perfect" parallelogram to begin with. angleToleranceInterval=0.05 feels alright to me at the moment. Let's try sharing out that version for folks to play with.

@jessegreenberg, can you make a new dev link that includes support for this query parameter and the update to the default sound collection (collection 1) from issue #4?

**Comment by BLFiedler** [comment] 2021-11-10 15:52
Also, I'll tag this onto this issue, since it appeared around the same time. Quoting myself from Slack and adding video:

> It looks like the sides are not interactable until one of the accompanying vertices is moved? You can see the pointer area doesn't quite fully generate until then.

https://user-images.githubusercontent.com/47331395/141146081-da61dd61-2cd7-4400-991c-45287fa21f6f.mov

@jessegreenberg mentioned it should be an easy fix, so appending this request to the new dev link which includes now:
1. Support for angleToleranceInterval query parameter
2. Success Sounds Collection 1 as default sound set on startup
3. Side interaction on startup fix

**Comment by BLFiedler** [comment] 2021-11-11 19:55
It occurred to me during Thursday meeting that these aren't scalable factors and dragging a side should result in an equal angle change for each pair... Also, the break seems to be asymmetric.

This might be more related to how we're calculating the angle?

**Comment by jessegreenberg** [comment] 2021-11-11 20:54
Just as a sanity check, I wanted to make sure that angles added up to 2 PI. The first set in https://github.com/phetsims/quadrilateral/issues/26#issue-1042730262 adds up to 6.28318530718 which is exactly the same as the sum of the second set 6.28318530718. This is exactly 2 * Math.PI which is good. I am actually surprised we didn't see more precision error.

> dragging a side should result in an equal angle change for each pair

@BLFiedler will that still be true when the quadrilateral is not a perfect parallelogram?

**Comment by BLFiedler** [comment] 2021-11-12 14:08
I think the answer to that is no. And that is more or less the sticking point I think and I'm not sure yet how to address that. 

Just to dig deeper on this, I did look at the sum of adjacent angles which for a parallelogram should be 180 degrees or PI. Here you can see the sum of the adjacent angles is changing as we change the shape, which more or less confirms your question.

![image](https://user-images.githubusercontent.com/47331395/141479492-efbeddce-bcec-45c7-9389-e65a0c0adde6.png)

Mathematically, the properties of a parallelogram are only true with absolute precision. If an angle is 1 degree off, well, it's just not a parallelogram. But we're asking the sim to say it is. 

This might need to be different based on how the shape is being controlled. 1 vertex vs. 2 vertices/1 side vs. 4 vertices/2 sides. The tangible might fall into the last category as well as multitouch with 4 fingers. My gut tells me that will behave most like we want without extra fixes. It's when the model (instead of the user) needs to constrain the parts of the shape that we are hitting this behavior. Not sure if that makes sense, but I can try to elaborate later. 

However, I'm a little uncertain why the break out of the ToleranceInterval happens on one side and not the other in the above video. Will have to think more.

Immediate ideas for discussion are:
1. correct to "perfect" parallelogram after entering ToleranceInterval and vertex is released
2. Change the tolerance interval when more than one vertex is moving
3. Something to do with the adjacent angles?
4. Any other ideas?

**Comment by jessegreenberg** [comment] 2021-11-15 22:39
In https://github.com/phetsims/quadrilateral/issues/26#issuecomment-965455854 @BLFiedler requested a new dev version with the query parameter for angle tolerance interval, a fix to the pointer areas on startup, and the first sound collection as default for the success paradigm.

Here is a version with these changes: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.11/phet/quadrilateral_en_phet.html?showPointerAreas&angleToleranceInterval=0.2

**Comment by BLFiedler** [comment] 2021-11-16 18:41
Add a scaling factor to angleToleranceInterval for the case where two or more are under control & you are in a parallelogram state. This increases the tolerance interval when the shape is changing after achieving a parallelogram to ease the task of maintaining a parallelogram.

**Comment by jessegreenberg** [comment] 2021-11-16 21:38
I am not sure how to implement the details in https://github.com/phetsims/quadrilateral/issues/26#issuecomment-970561939, lets schedule a brief meeting before proceeding.

**Comment by BLFiedler** [comment] 2021-11-19 20:30
I think this is analagous to what MK put in place for Ratio and proportion, so there may be issues or commits related. I'll see if I can find them.

I think the expected behavior is:
angleToleranceInterval becomes angleToleranceInterval * (Scaling Factor) when **both** of these are true:
1.) More than one vertex is being moved (e.g., 2 or more vertices or 1 or more sides).
2.) Prior to movement, the shape was a parallelogram (within the original angleToleranceInterval)
The purpose is, once a learner has achieved a parallelogram, to make it easier to maintain a parallelogram by widening the angleToleranceInterval when the user is moving multiple vertices. Also, to reduce the likelihood of receiving feedback that you are no longer in a parallelogram while moving a side(s).

**Comment by BLFiedler** [comment] 2021-11-22 15:51
A small bit of organization based on our current desired implementation:

### Tolerance value to determine parallel based on interaction and current shape:

#### Not a Parallelogram
- Moving 1 vertex: `angleToleranceInterval`
- Moving 2+ vertices (inc. a side): `angleToleranceInterval`

#### A Parallelogram 
- Moving 1 vertex: `angleToleranceInterval`
- Moving 2+ vertices (inc. a side): `angleToleranceInterval * scaleFactor`

note: scaleFactor name only used for illustrative purposes.

**Comment by BLFiedler** [comment] 2022-01-18 17:10
If simple to make a separate case for interacting with a side, can make the `scaleFactor` effectively infinite (make it impossible to not be a parallelogram.

**Comment by jessegreenberg** [comment] 2022-01-18 20:49
OK, committed. Here is the logic:

```js
        if ( anySidesPressed && this.isParallelogramProperty.value ) {

          // A side has been picked up while the shape is a parallelogram - it should be impossible for the shape
          // to go "out" of parallelogram in this case because none of the angles should be changing.
          toleranceInterval = Number.POSITIVE_INFINITY;
        }
        else if ( numberOfVerticesPressed >= 2 ) {

          // Two or more vertices pressed at once, increase the tolerance interval by a scale factor so that
          // it is easier to find and remain a parallelogram with this input
          toleranceInterval = QuadrilateralQueryParameters.angleToleranceInterval * QuadrilateralQueryParameters.angleToleranceIntervalScaleFactor;
        }
        else if ( numberOfVerticesPressed === 1 ) {

          // Only one vertex is moving, we can afford to be as precise as possible from this form of input, and
          // so we have the smallest tolerance interval.
          toleranceInterval = QuadrilateralQueryParameters.angleToleranceInterval;
        }
        else {

          // We are dragging a side while out of parallelogram, or we just released all sides and vertices. Do NOT
          // change the angleToleranceInterval because we don't want the quadrilateral to suddenly appear out of
          // parallelogram at the end of the interaction. The ternary handles initialization.
          toleranceInterval = this.angleToleranceIntervalProperty ? this.angleToleranceIntervalProperty.value : QuadrilateralQueryParameters.angleToleranceInterval;
        }
```

The last case makes sure we don't suddenly snap "out" of parallelogram at the end of an interaction since that would otherwise reduce the tolerance interval to a smaller value.

The scale factor for when 2 or more vertices are being moved at once is controlled with query parameter ?angleToToleranceIntervalScaleFactor. Default value is 2. 

@BLFiedler can you please review?

**Comment by BLFiedler** [comment] 2022-01-20 18:08
Great! I think this works very well for touch/cursor input. I think the goal of this issue is complete. I have two thoughts currently to split into separate issues, one more immediate and one just to check back on later.

1. Tangible input doesn't benefit from the 'pressed' property in changing the angleToleranceProperty #47 

2. I created an issue to make sure there's a final check on the default values prior to research deployment - but this is mostly for me and will remain assigned to me. (https://github.com/phetsims/quadrilateral/issues/48)

Otherwise, closing this issue.

**Closed by BLFiedler** 2022-01-20 18:08 UTC
Labels: priority:1-top, status:ready-for-review
