### ISSUE TITLE
Sounds when state is set or launched

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/quadrilateral#82] opened 2022-02-25 19:12 UTC
For https://github.com/phetsims/phet-io/issues/1626. Seen on Win 11 Chrome, and particularly Firefox.
When the sim is launched a sound will play (in Firefox) whether the shape is green or yellow. In state, this seems to happen more when the shape is green.

https://user-images.githubusercontent.com/41024075/155773704-5570619a-6499-4b84-8adf-6755185f8a1a.MOV

https://user-images.githubusercontent.com/41024075/155773710-f255dc10-e4f4-42b7-a094-cfe606817103.MOV

https://user-images.githubusercontent.com/41024075/155773714-b7abe047-7f48-4d24-bb06-0ede0f5fee3a.MOV

**Comment by zepumph** [comment] 2022-02-25 20:20
I know that PhET-iO may not be on the forefront of work being done in this sim right now, but it is good to have the issue report. Thanks @KatieWoe.

**Comment by jessegreenberg** [comment] 2022-03-01 23:46
I just fixed a similar issue that was unlrelated to phet-io but may have caused this, #87 -  @KatieWoe can you see if this has been fixed on master?

**Comment by Nancy-Salpepi** [comment] 2022-03-02 18:45
I was unable to reproduce the sounds originally reported in this issue on Mac + Chrome/Safari/Firefox or on Win10 + Chrome/Firefox.

I know that PhET-iO probably isn't being worked on right now, but I did want to report other unusual sounds I noticed. I wasn't sure if I should open a separate issue or not for them at this time. 

1. Using Chrome (either MacOS or Windows), when I open the State wrapper, the organ sound plays over and over. If I reload the page, the sound stops. 

https://user-images.githubusercontent.com/87318828/156425782-7a166b8b-491e-4915-b9c0-bc107b9615c7.mov

<br>
2. After the sim is launched in Studio, or the state is set in the State wrapper with the green quadrilateral showing, pressing the reset all button produces the organ sound. If the state was set with the yellow quadrilateral, then just the reset all button sound is heard. 

https://user-images.githubusercontent.com/87318828/156426760-97005167-e07c-40d2-9bdc-93f72578bd4e.mov

**Comment by zepumph** [comment] 2022-03-02 18:50
This is helpful to report here, thanks. We may not work on this until phet-io get's a sprint in this sim. Unassigning.

**Comment by jessegreenberg** [comment] 2022-03-02 19:01
Thanks for testing @Nancy-Salpepi, that issue is good to know. I could definitely see the current sound implementation causing that in the state wrapper. We should come back to this after sound design becomes more final and we begin to work on PhET-iO in this sim. Unassigning.

**Comment by BLFiedler** [comment] 2022-12-22 21:59
Not publishing with these PhET-iO features

**Closed by BLFiedler** 2022-12-22 21:59 UTC
Labels: type:bug, dev:phet-io, dev:sound, phet-io:save-and-load
