### ISSUE TITLE
alt + shift + r changes window size

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/quadrilateral#329] opened 2023-01-11 21:28 UTC
**Test device**
chromebook and mac

**Browser**
chrome 

**Problem description**
For https://github.com/phetsims/qa/issues/879, using the shortcut alt/opt + shift + r  results in the window resizing.

**Visuals**
<img width="1382" alt="Screenshot 2023-01-11 at 4 26 57 PM" src="https://user-images.githubusercontent.com/87318828/211921427-53aafdd1-c0f8-4361-93e0-3c5099bfd445.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Quadrilateral‬
URL: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.73/phet/quadrilateral_all_phet.html
Version: 1.0.0-dev.73 2023-01-08 23:48:12 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1482x788
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment] 2023-01-11 21:45
Oooh that's good to know, thanks @Nancy-Salpepi.

@terracoda what would you like to do about this? We could try to prevent this from happening or change the key combination.

**Comment by terracoda** [comment] 2023-01-12 16:38
And did the partial reset work on other platforms/browser combos?
I am quite baffled and I have been able to reproduce the behaviour on my Mac (12.6.2).

**Comment by jessegreenberg** [comment] 2023-01-12 17:24
I just tried on my Chromebook - the window docking hotkey for me is Alt + ].

**Comment by Nancy-Salpepi** [comment] 2023-01-12 18:08
I don't know what "Rectangle" is and looking at my list of applications I don't see it. 
On the Chromebook alt + ] also changes the window size for me in addition to alt + shift + r.
I asked @stemilymill to take a look on her mac.

**Comment by Nancy-Salpepi** [comment] 2023-01-12 18:35
@stemilymill realized that it was happening because we have a window resizer plugin on chrome. I guess that is what you meant by rectangle @jessegreenberg. When disabled, the resizing doesn't occur and keys work as they should.

**Comment by jessegreenberg** [comment] 2023-01-12 18:38
Yes, that is what I meant - sorry I wasn't clear. "Rectangle" was an equivalent one for macOS. Do you have an app on macOS causing the resizing?

**Comment by Nancy-Salpepi** [comment] 2023-01-12 19:31
The plugin is called Window Resizer--so every computer I used, I was signed into google chrome and that is why I was seeing it on all my devices.

**Comment by jessegreenberg** [comment] 2023-01-12 19:44
Ahh, thanks. That makes sense. @terracoda can you review this issue and comment if we should do anything else? I am not sure if `preventDefault` will stop a plugin and I am not sure if it should. I kind of don't think so.

**Comment by terracoda** [comment] 2023-01-14 12:10
Thanks for confirming the plugin was the issue. I think I did read something about a plugin while was searching! 

One more question, do both reset shortcuts cause the resizing behaviour, or just the one mentioned?

**Comment by Nancy-Salpepi** [comment] 2023-01-17 13:04
@terracoda it was just the one I mentioned. The other worked fine 🙂.

**Comment by terracoda** [comment] 2023-01-18 01:15
Thanks @Nancy-Salpepi! That's helpful as that is the shortcut, I originally wanted to use to "Reset Shape".

From the screenshot in https://github.com/phetsims/quadrilateral/issues/329#issue-1529722971, the shape is a small square, does that mean the shortcut reset the shape and resized the window?

I don't really want to change the shortcut, but it is difficult for me to gauge how serious the issue is.

**Comment by terracoda** [comment] 2023-01-18 01:44
@Nancy-Salpepi also mentioned that when the "window resizer plugin" is disabled the shortcut works as intended.

I just looked up what Window Resizer is mainly used for, and it seems to be a very popular tool for testing responsive websites.

I think we do not have to change the shortcut. This may not be a popular plugin for teachers and learners.

**Comment by terracoda** [comment] 2023-01-18 01:46
@jessegreenberg, I feel comfortable leaving the shortcut as is.
Closing.

**Closed by terracoda** 2023-01-18 01:46 UTC
Labels: type:bug, dev:alt-input
