### ISSUE TITLE
Corner Guide a bit wonky sometimes around 180 degrees

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#233] opened 2022-10-06 02:40 UTC
<img width="410" alt="image" src="https://user-images.githubusercontent.com/1902116/194201677-90ee88f9-ccaf-420d-9a52-c8d6c90e01a6.png">

Happens sometimes with keyboard.
Doesn't seem to happen with mouse.
When I go back to keyboard after using mouse, the issue seems resolve itself.

**Comment by jessegreenberg** [comment] 2022-10-11 21:59
Sorry @terracoda I tried for almost ten minutes to reproduce this and could not. Is this still happening for you? If so, can you do it with ?showModelValues? Is "Fine Input Spacing" enabled?

**Comment by terracoda** [comment] 2022-10-12 14:04
Yep, will try to isolate the event. Thanks for trying :-)

**Comment by jessegreenberg** [comment] 2022-10-12 16:23
Aha! I found a case for this while testing #231 
![image](https://user-images.githubusercontent.com/6396244/195396575-4a6781c4-8d1d-4af3-88a6-cd22e934ce03.png)

Then I moved the vertex around and the problem went away and I have not been able to get it to happen again.

**Comment by terracoda** [comment] 2022-10-12 17:34
Ok, I have model values show here.
All Sim Voicing options are checked, and I am **not** using fine input in this case.
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/1902116/195410085-a684cde0-75d9-44ac-ad4b-ae0fc13685b1.png">

**Comment by terracoda** [comment] 2022-10-12 17:35
The fan stayed wonky after moving down then up to flat again, but once i went inward into a Dart and then back down and up, the fan was fine.

**Comment by jessegreenberg** [comment] 2022-10-12 21:28
It looks like in all examples of this happening there is exactly one too many slices shown when the angle is 180 degrees. That should help identify where the bug is.

**Comment by jessegreenberg** [comment] 2022-10-12 22:25
The problem is here: 
```js
      // now draw the remainder - check to make sure that it is large enough to display because ellipticalArcTo doesn't
      // work with angles that are close to zero.
      const remainingAngle = definedAngle % SLICE_SIZE_RADIANS;
      if ( remainingAngle > 0.0005 ) {
```

![image](https://user-images.githubusercontent.com/6396244/195458989-c0d2a68b-9f52-49ae-b54c-4d239f9318e2.png)

The difference between the angle and Math.PI is within amount of precision error. Since definedAngle is less than PI the remainder is just under SLICE_SIZE_RADIANS so we see almost an extra full slice.

**Comment by jessegreenberg** [comment] 2022-10-13 22:26
This was fixed by getting the remainder without using the modulus operator. @terracoda please let me know if you ever see this again!

**Closed by jessegreenberg** 2022-10-13 22:26 UTC
Labels: type:bug
