### ISSUE TITLE
Possible for sides out of parallel to be considered parallel by the model

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quadrilateral#156] opened 2022-05-23 18:07 UTC
Related to changes from https://github.com/phetsims/quadrilateral/issues/108, it is possible for the model to incorrectly report that sides are parallel. To reproduce:

1) Create a trapezoid.
2) Click on one of the parallel sides. This will set the `angleToleranceInterval` for that pair of parallel sides to Infinity.
3) Drag one of the non-parallel sides so that the parallel sides tilt out of parallel.

The `angleToleranceInterval` for the previously parallel sides is still infinity so they are still considered parallel by the model

![image](https://user-images.githubusercontent.com/6396244/169880593-3e210cb7-1a70-42f3-955a-69a8706ea22f.png)

**Comment by jessegreenberg** [comment] 2022-05-23 18:08
Found by @terracoda during https://github.com/phetsims/quadrilateral/issues/154.

**Comment by jessegreenberg** [comment] 2022-05-23 19:12
I tried this approach:

```js
        else if ( anyOtherSidesPressed && !this.isParallelProperty.value ) {

          // The other sides are being pressed and my sides are not currently parallel. While dragging a side we
          // do not want the shape to become a parallelogram within a finite angleToleranceInterval so make sure
          // my sides will never become parallel.
          toleranceInterval = Number.NEGATIVE_INFINITY;
        }
        else if ( anyOtherSidesPressed && this.isParallelProperty.value ) {

          // The other sides are being pressed and my sides are currently parallel. It is possible in this case
          // that my sides go in/out of parallel while they move, so reduce the tolerance interval to a defined value.
          toleranceInterval = QuadrilateralQueryParameters.angleToleranceInterval;
        }
```

But it doesn't fix the case where sides start out of parallel in https://github.com/phetsims/quadrilateral/issues/156#issuecomment-1135001934. @BLFiedler can we discuss this issue tomorrow during model meeting?

**Comment by jessegreenberg** [comment] 2022-05-24 15:58
Ugh "resolves" automatically closes an issue...

@BLFiedler @terracoda and I discussed this today and decided to go with https://github.com/phetsims/quadrilateral/issues/156#issuecomment-1135043565 for now, even though it reintroduces https://github.com/phetsims/quadrilateral/issues/108#issuecomment-1090402804. I think @BLFiedler was going to test this, assigning to him. But the sentiment today was that this would be sufficient for June 11 tests.

**Comment by BLFiedler** [comment] 2022-08-16 19:23
To be addressed in the near future:

Tolerance-sourced errors
- It is possible to move from Convex < - > Trapezoid with side drag.
- It is possible to move from Trapezoid < - > Parallelogram with side drag.

It's likely we'll need to create some case-by-case interventions for each of these based on the shape detection and side-focused interaction.

I'll do some more thinking here before assigning for solutions.

**Comment by BLFiedler** [comment] 2022-09-01 14:39
With our more stringent requirements for a parallelogram introduced in the latest shape detection model in #188 , I have been unable to reproduce this. Closing.

**Closed by BLFiedler** 2022-09-01 14:39 UTC
Labels: dev:model, priority:2-high
