### ISSUE TITLE
Description and Visual using different tolerances

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#261] opened 2022-11-22 20:46 UTC
While testing #237 I found the following issue:

When moving B up from a right angle (as part of a Kite,) it remains a right angle and becomes part of a Trapezoid.

The tolerances for the visual and the description are different, so the description does not match the visuals.

Starting step
<img width="785" alt="image" src="https://user-images.githubusercontent.com/1902116/203415597-97d1b30b-0616-4986-8f6c-67584ce7fa26.png">
Moving B up one step,
I hear , "similar but smaller than corner C"
<img width="786" alt="image" src="https://user-images.githubusercontent.com/1902116/203415528-c5396197-a38b-473b-82a0-67f8495c8eba.png">

On slack @jessegreenberg said 
> It is because the comparison description uses interAngleToleranceInterval but the visual indicator uses staticAngleToleranceInterval.

If B is supposed to be 90 degrees in step 2, then I should hear:
"right angle, equal to Corner C"

**Comment by jessegreenberg** [comment] 2022-11-22 22:27
I'm not sure how our tolerance implementation can support this case. @BLFiedler do you have any thoughts?

We could add special cases for description to do describe them as equal if both angles are within `interAngleToleranceInterval`?

**Comment by terracoda** [comment] 2022-11-23 15:59
Just noting today with fresh pull, another case...to help the conversation
<img width="785" alt="image" src="https://user-images.githubusercontent.com/1902116/203592204-c10a4741-1e95-4888-9648-b0d11c675b63.png">

**Comment by terracoda** [comment] 2022-11-23 17:07
In contrast, moving corner D in this triangle case, I visually have a right angle for 5 key presses and the description matches.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/1902116/203607166-967c465e-bddf-4f13-ac6c-608b3c804fcf.png">

**Comment by jessegreenberg** [comment] 2022-11-29 17:40
During the meeting today we identified that this is NOT an issue with `angleToleranceInterval` vs `interAngleToleranceInterval`. The issue is this special case added for describing angles for trapezoids:

```js

    // If we are a trapezoid, only describe angles as equal when they are EXACTLY equal, otherwise we may run into
    // cases where we move out of isoceles trapezoid while the angles are still described as "equal".
    const usableToleranceInterval = shapeName === NamedQuadrilateral.TRAPEZOID ? 0 : interAngleToleranceInterval;
```

**Comment by terracoda** [comment] 2022-11-30 15:47
Not sure if this is the same issue, but I think it is related to length tolerance, so I am putting it here for now.
I know we are working on tolerances for trapezoids in some issue.

In the case below, the shape name is Trapezoid and it looks very much like a Trapezoid. Sides AB and CD are not equal in the model values, but they are close enough to both be "Just over 4 units, equal to opposite side." I think the test/tolerance for an Isosceles Trapezoid needs to be slightly more exact - smaller than the default key press?

If we did that would this conflict with what we are did to be able to find a Rhombus from a Square?. 

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/1902116/204842280-428e8399-3546-42da-b2e6-4c6d2ab0b6b7.png">

**Comment by BLFiedler** [comment] 2022-11-30 18:25
This has led me down a much-too-deep rabbit hole on how the tolerances are handled for different side lengths and angle differences, as well as how shapes with mixed angle/length requirements interact with the tolerances. 

There likely isn't going to be a robust solution here and we may need to continue to build a few special cases for description (not ideal), but I'll need to think on it a bit more.

**Comment by BLFiedler** [comment] 2022-12-14 16:30
Ugh ,sorry, I forgot to assign for the above TODO. Not the end of this issue as we've seen some things arise in #281 and #269, but a step closer.

**Comment by jessegreenberg** [comment] 2022-12-15 16:40
The above commits (I believe) are what are needed. But they ended up being extremely complicated and disruptive. I am seeing bugs falling out of these changes and the code is worse off for it. I am not confident that it is worth proceeding

@BLFiedler and I also discussed other cases that will come up because of tolerance problems that will not be fixed by this change. I am going to revert these changes while we (mostly @BLFiedler, thank you!) continues to think on this.

**Comment by jessegreenberg** [comment] 2022-12-15 16:47
Reassigning to @BLFiedler for now.

**Comment by terracoda** [comment] 2022-12-16 14:34
I think this idea is related to this issue. 
I mapped out a proposed idea for side-length units that would need to correspond to any changes in step size. We can discuss at today's meeting. Basically, wondering if quarters works/sounds better than "just under", "just over", etc.
![image](https://user-images.githubusercontent.com/1902116/208121048-218d6c15-bb75-4e69-9a2b-e876da609a55.png)

**Comment by BLFiedler** [comment] 2022-12-16 17:47
@terracoda , you might want to move the above comment to its own issue around aligning the described lengths with the adjusted "quarter grid" step sizes.

**Comment by BLFiedler** [comment] 2022-12-16 17:48
Leaving this issue, #269, and #281 open for now, but they should be irrelevant with the tolerance changes and step size changes. Self assigning to close if no further conflicts are found.

**Comment by BLFiedler** [comment] 2023-01-05 16:10
Nothing has come up recently. I will close this and let new issues come up during dev test.

**Closed by BLFiedler** 2023-01-05 16:10 UTC
Labels: type:bug
