### ISSUE TITLE
Object Responses with keyboard input

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#182] opened 2022-07-27 19:18 UTC
Ok, apologies for the long delay. 
I have some example object response for corners and sides sketched out in a document. It is not perfect, but hopefully it is enough to get simple object responses implemented.

Please see https://docs.google.com/document/d/1RN9gIFM3D-Mj6y8fFZgD4XHDrqkm3qiRUaZ7FOcwfGg/edit?usp=sharing

Here's a summary of the parameters:
**Moving corners**
When moving corners, I think we can get away from using directional parameters like "up, left, down, right" and just use angle changes ("smaller/ wider/ right angle") and then use relative proximity changes in physical distance from the opposite corner ("closer to" or "farther from" or "equal to").

**Examples for corner object responses:**
- angle {{wider}}, {{closer to}} opposite corner
- angle {{smaller}}, {{farther from}} opposite corner
- {{right angle}}, {{equal to}} opposite corner
- angle {{smaller}}, {{equal to}} opposite corner

**Moving sides is trickier**
When moving a side, I think for now we need to use the directional parameters "up, left, down, right". I haven't thought of alternative yet. The context responses describe changes in tilt and changes in area, so I decided to have the object responses describe length changes of the adjacent sides. Not sure if this will be confusing or not.

**Examples for side object responses:**
- right, adjacent sides {{shorter}}
- right, adjacent sides {{longer}}
- up, adjacent sides {{longer}}
- up, {{equal to}} adjacent sides

I hope this covers object responses in a simple manner. I may not have thought of everything.

**Comment by jessegreenberg** [comment] 2022-08-01 22:54
Responses are in place in the above commits. I am almost satisfied with this, but I think there is an issue with UtteranceQueue interruption.

So far I have implemented the object responses and context responses separately from natural code separation. Context responses in QuadrilateralAlerter, and object responses in each view class VertexNode and SideNode because object responses are triggered from input listeners on those Nodes. The problem is that since they are in different files they use different Utterances for the UtteranceQueue. The Object responses take priority over the context responses so that each input clears any stale info. But that means that critical responses related to all right angles or all sides equal can be missed if you rapidly press arrow keys.

The fix is to move all responses into the same file so they can be packaged into a `ResponsePacket` and we don't have to use the UtteranceQueue. The challenge will be in doing this but still only triggering these object responses from keyboard input.

**Comment by jessegreenberg** [comment] 2022-08-02 15:06
OK, I think this is working well now. @terracoda ready for you to review. I built a dev version to get around phettest being unpredictable: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.43/phet/quadrilateral_en_phet.html

Hopefully the Priority of Utterances is working as expected.  As we decided while working on context responses, responses about 
all lengths equal/all sides equal/found a parallelogram/lost a parallelogram  are high priority and cannot be interrupted. Otherwise, new object responses and/or context responses responses about changing shape have a priority such that new input will interrupt old responses.

**Comment by jessegreenberg** [comment] 2022-08-02 16:54
Discussed during meeting today:

- Shape name/in or out of parallelogram/ all right angles/all equal sides is highest priority. It won't be interrupted by anything except itself.
- Other context responses will be "medium" priority, they will not interrupt the above content, and they cannot be interrupted by new object responses.
- Object responses (without a context responses) is lowest priority. It will never interrupt a response if it has a context response.

It is important that the context response is always heard. We want a response every key press, but it does not need to interrupt the announcing context response.

@terracoda also said we may want to flush the object responses from the queue when a new context response is announced.

**Comment by jessegreenberg** [comment] 2022-08-02 16:58
@terracoda also mentioned there is a case that needs to be designed when moving a side where one adjacent side grows and another shrinks so assigning to her as well.

**Comment by jessegreenberg** [comment] 2022-08-02 17:15
OK here is a new version with these changes in Utterance priority. It should be working as described in https://github.com/phetsims/quadrilateral/issues/182#issuecomment-1202985158

**Comment by terracoda** [comment] 2022-08-05 20:33
Ok, @jessegreenberg, for sides I am having a lot of trouble, but I think I will go with the idea you suggested for the case where the length of the adjacent sides change unequally - one getting shorter and the other getting longer.

Here's my pseudo-logic that I hope covers the scenarios better now when moving a side

1. Change in proximity to the opposite side AND the same or similar side length changes to adjacent sides. (e.g. moving a side of a parallelogram) - _describe both changes in length (shorter/longer) and changes in proximity (closer to/farther from)._
2. NO change in proximity AND no change or no significant change (tolerances!) in side length - _just describe direction in this case._ 
3. Change in proximity AND NO changes in length of adjacent sides - _I don’t think this is possible_
4. NO change in proximity AND different side length changes to adjacent sides -  _just describe “adjacent sides change unequally” (this will be repetitive until we get feedback)_
5. Change in proximity to the opposite side AND different side length changes to adjacent sides. (moving the side of some other quads - e.g., trapezoids) - describe “adjacent sides change unequally” and changes in proximity (closer to/farther from) the opposite side

There a examples in the design doc. I hope the examples and logic are clear enough.

**Comment by terracoda** [comment] 2022-08-16 14:29
@jessegreenberg, I forgot to assign this issue to you 11 days ago.

**Comment by jessegreenberg** [comment] 2022-08-17 00:03
OK this is done in https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.53/phet/quadrilateral_en_phet.html - @terracoda back to you to review.

We discuss on slack challenges about the "proximity to opposite side description". Here is the logic I went with to produce dev.53.

```
 IF length change for first adjacent side OR second adjacent side are larger than DESCRIBE_LONGER_ADJACENT_SIDES_THRESHOLD
  IF length change for first adjacent side AND length change for second adjacent side are larger than  BOTH_ADJACENT_SIDES_CHANGE_THE_SAME_THRESHOLD
    describe as "adjacent sides longer/shorter"
  ELSE
    describe as "adjacent sides change unequally"
  
  IF length change for first adjacent side AND length change for second adjacent side are larger than DESCRIBE_CLOSER_TO_OPPOSITE_SIDE_THRESHOLD
    Include the phrase "farther from/closer to opposite side"
ELSE
  Just describe as "right/left/up/down"
```

Constants have values
```js
const DESCRIBE_CLOSER_TO_OPPOSITE_SIDE_THRESHOLD = 0.04;
const DESCRIBE_LONGER_ADJACENT_SIDES_THRESHOLD = 0.002;
const BOTH_ADJACENT_SIDES_CHANGE_THE_SAME_THRESHOLD = 0.001;
```

With these values I never hear "right/left/up/down". But the values are small enough so that with initial sim conditions we hear "adjacent sides get longer" or "adjacent sides get shorter, closer to opposite side".

**Comment by terracoda** [comment] 2022-08-17 17:29
I hear the directional cues a occasionally, but not often. I heard them a couple of times during session with consultant.
I often do not hear context responses (shape getting smaller/bigger or sides tilting/straightening), just object responses. This is likely due to object responses having priority over context responses. Can we switch that priority? I think context responses should over-ride object responses if we end up using priority levels.

**Comment by terracoda** [comment] 2022-08-17 17:46
Some general feedback from adult consultant:
- "comparable" is not clear, and also too big of a word for 3rd graders.
- "adjacent sides change unequally", also not so clear. Not clear how they are changing if they are changing unequally. 
- liked when opposites were described
- liked most when things were equal, when corners were right angles, and when opposite sides were parallel.

Maybe instead of:
- Object response: "Adjacent sides change unequally." + "Opposite Sides {{AB}} and {{DC}} tilt in Parallel as shape gets bigger/smaller" ...
We name the sides that are changing in object response then describe the tilt or size of shape:
- "Side {{DA}} longer, Side {{BC}} shorter" + "Opposite Sides AB and DC tilt in parallel and shape gets bigger/smaller"

Note that object responses can get state quickly, so I think in general they should be lowest priority if we use priority levels.

**Comment by terracoda** [comment] 2022-09-01 15:43
Need to consider new context responses in #198 when re-thinking Object Responses.

The responses need to go together to scaffold an understanding of the shape and shape transformations.

**Comment by terracoda** [comment] 2022-09-20 20:28
@jessegreenberg, you implemented theses object responses nicely.
I am going to close this issue and work on iterations to the content of the responses in new issues.

Before closing, just want to note that I hadn't intended to restrict object responses to keyboard only. For this sim it seems to be working nicely.

If they don't remain restricted, or they can't remain restricted, it just means we'll need to sort out special timing for mouse-driven object responses like we have done in other sims.

**Closed** 2022-09-20 20:31 UTC
Labels: meeting:design, dev:voicing, design:voicing
